_security_logout:
    resource: security.route_loader.logout
    type: service

login:
    path: /login
    controller: App\Action\Auth\LoginAction

register:
    path: /register
    controller: App\Action\Auth\RegisterAction
