# Read docs: https://symfony.com/doc/current/bundles/StofDoctrineExtensionsBundle/index.html
# DoctrineExtensions docs: https://github.com/doctrine-extensions/DoctrineExtensions/tree/main/doc
stof_doctrine_extensions:
    default_locale: en_US
    orm:
        default:
            timestampable: true
